const STAR_WARS_API_URL = process.env.NEXT_PUBLIC_STAR_WARS_API_URL;

const MAX_FILMS_LENGTH = 6;
const MAX_CHARACTERS_LENGTH = 82;
const MAX_STARSHIPS_LENGTH = 36;

const MAX_FILM_SPECIAL_STICKER_PACK = 6;
const MAX_CHARACTER_SPECIAL_STICKER_PACK = 20;
const MAX_STARSHIP_SPECIAL_STICKER_PACK = 10;

export {
  STAR_WARS_API_URL,
  MAX_FILMS_LENGTH,
  MAX_CHARACTERS_LENGTH,
  MAX_STARSHIPS_LENGTH,
  MAX_FILM_SPECIAL_STICKER_PACK,
  MAX_CHARACTER_SPECIAL_STICKER_PACK,
  MAX_STARSHIP_SPECIAL_STICKER_PACK,
};
