const STAR_WARS_API_URL = process.env.NEXT_PUBLIC_STAR_WARS_API_URL;

const MAX_MOVIES_LENGTH = 6;
const MAX_CHARACTERS_LENGTH = 82;
const MAX_SPACECRAFT_LENGTH = 36;

export {
  STAR_WARS_API_URL,
  MAX_MOVIES_LENGTH,
  MAX_CHARACTERS_LENGTH,
  MAX_SPACECRAFT_LENGTH,
};
