const STAR_WARS_API_URL = process.env.NEXT_PUBLIC_STAR_WARS_API_URL;

const MAX_FILM_SPECIAL_STICKER_PACK = 6;
const MAX_CHARACTER_SPECIAL_STICKER_PACK = 20;
const MAX_STARSHIP_SPECIAL_STICKER_PACK = 10;

const MAX_STICKERS_PACK = 4;

const EXTRACT_ID_REGEX = /\/([^\/]+)\/?$/;

export {
  MAX_STICKERS_PACK,
  STAR_WARS_API_URL,
  MAX_FILM_SPECIAL_STICKER_PACK,
  MAX_CHARACTER_SPECIAL_STICKER_PACK,
  MAX_STARSHIP_SPECIAL_STICKER_PACK,
  EXTRACT_ID_REGEX,
};
